config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'Groupe-Oberlin/', to: 'users#show'
    get 'Groupe-Oberlin/new-article', to: 'users#new_article'
    post 'Groupe-Oberlin/new-article', to: 'users#create_article'
    get 'Groupe-Oberlin/article/:id', to: 'users#article', as: 'Groupe-Oberlin/article/'
    get 'Groupe-Oberlin/Messages', to: 'users#messages'
    get 'Groupe-Oberlin/Comments', to: 'users#comments'
  end

  get 'admin/login', to: 'sessions#new'
  post 'admin/login', to: 'sessions#create'
  delete 'admin/logout', to: 'sessions#destroy'

  get 'news-details/:id' => 'news#show', as: 'news-details'
  post 'news-details/:id' => 'news#comment'

  get 'emploi' => 'emploi#index'

  get 'faq' => 'contact#faq'

  get 'contact' => 'contact#index'
  post 'contact' => 'contact#send_message'

  get 'a-propos' => 'welcome#a-propos'

  get 'news' => 'news#index'

  get 'oberlin-transit' => 'filliales#transit'

  get 'oberlin-tourisme' => 'filliales#tourisme'

  get 'oberlin-services' => 'filliales#services'

  get 'oberlin-it' => 'filliales#it'

  get 'oberlin-ingenierie' => 'filliales#ingenierie'

  get 'oberlin-immo' => 'filliales#immo'

  get 'oberlin-construction' => 'filliales#construction'

  get 'oberlin-arts' => 'filliales#arts'

  get 'oberlin-agro' => 'filliales#agro'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@articles = Blog.all
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/a-propos.html.erb
<% title "À Propos" %>

<%= render "layouts/shared/header" %>

<div class="breadcrumb-section image-bg ">
  <div class="overlay"></div>
  <div class="breadcrumb-content container">
    <h1>À Propos de Nous</h1>
    <ol class="breadcrumb">
      <li><a href="/">Accueil</a></li>
      <li class="active">À Propos</li>
    </ol>
  </div>
</div><!-- breadcrumb-section -->

<div class="about-us-section section-padding">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="about-section-content">
          <h2>Groupe Oberlin</h2>
          <p>
            Partenaire pour de multiples types de missions, le Groupe OBERLIN s'est doté des outils
            les plus modernes et des ressources humaines compétentes.
            En plus de notre travail de qualité supérieure, nos clients
            tirent profit d'un point d'accès unique qui élimine le besoin d'avoir recours à des prestataires multiples.
            Selon les besoins des clients, nous sommes en mesure de proposer des solutions pertinentes qui
            répondent à leurs exigences et qui respectent leur budget.
          </p>

          <h2>Historique</h2>
          <p>
            Né de la volonté d’entreprendre de ses fondateurs, le Groupe OBERLIN est fondé en 2011.
            Il est l’aboutissement de nombreux efforts d’entreprendre fait de réussites et de moins-biens.
            L’activité a débuté par la mise en relation d’affaires de partenaires et, petit à petit l’entreprise
            s’est bâtie é partir du recrutement de ressources humaines du niveau de ses ambitions.
          </p>

          <h2>Vision</h2>
          <p>
            Le Groupe OBERLIN se veut être un portail d’accès à des services diversifiés et tous orientes
            vers la création de valeur ajoutée. A la base il est un mouvement ayant pour but d’octroyer des
            opportunités d’expression de talents et de compétences à la jeunesse de l’Afrique et du monde.
            Sa philosophie socle est de construire l’individu pour construire une nation.
          </p>

          <h2>Objectifs</h2>
          <p>
            Construire un Groupe entrepreneurial fort et diversifié au service des personnes,
            des entreprises et des états. Donner un cadre d’expression au talent des jeunes et
            participer activement à la construction de notre Afrique restent pour nous des préoccupations fortes.
          </p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="about-us-image">
          <%= image_tag("about/about.jpg",  alt: "", class: "img-responsive") %>
        </div>
      </div>
    </div><!-- row -->
  </div><!-- container -->
</div><!-- features section -->

<!--<div class="work-process image-bg section-padding">
  <div class="overlay"></div>
  <div class="container">
    <div class="section-title text-center">
      <h1>Why Choose Us</h1>
      <h2>Our Promise and Values</h2>
    </div>
    <div class="process-section">

      <div class="row">
        <div class="col-md-6 col-sm-12">
          <div class="work-proces left-content text-right">
            <div class="process-icon">
              <%= image_tag("process/proces1.png",  alt: "image", class: "img-responsive") %>
            </div>
            <div class="process-info">
              <h4>Work Strategy</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod fore to tempor incididunt ut labore et dolore magna aliqua ut enim ad.</p>
            </div>
          </div>
          <div class="work-proces left-content text-right">
            <div class="process-icon">
              <%= image_tag("process/proces2.png",  alt: "image", class: "img-responsive") %>
            </div>
            <div class="process-info">
              <h4>Best Quality</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod fore to tempor incididunt ut labore et dolore magna aliqua ut enim ad.</p>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-sm-12">

          <div class="work-proces">
            <div class="process-icon">
              <%= image_tag("process/proces3.png",  alt: "image", class: "img-responsive") %>
            </div>
            <div class="process-info">
              <h4>Specialist Engineers</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod fore to tempor incididunt ut labore et dolore magna aliqua ut enim ad.</p>
            </div>
          </div>
          <div class="work-proces">
            <div class="process-icon">
              <%= image_tag("process/proces4.png",  alt: "image", class: "img-responsive") %>
            </div>
            <div class="process-info">
              <h4>Skilled Workers</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod fore to tempor incididunt ut labore et dolore magna aliqua ut enim ad.</p>
            </div>
          </div>
        </div>
      </div>
    </div>&lt;!&ndash; row &ndash;&gt;
  </div>&lt;!&ndash; container &ndash;&gt;
</div>&lt;!&ndash; process &ndash;&gt;-->

<!--<div class="team-section section-padding">
  <div class="container">
    <div class="section-title text-center">
      <h1>OUR Team</h1>
      <h2>We have Experienced Members</h2>
    </div>

    <div class="team-members">
      <div class="row">
        <div class="col-sm-3">
          <div class="team-member">
            <div class="member-image">
              <%= image_tag("team/4.jpg",  alt: "image", class: "img-responsive") %>
            </div>
            <div class="team-info">
              <div class="member-info">
                <h4>Jhon Doe</h4>
                <p>Construction Manager</p>
              </div>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod fore to tempor incididunt</p>
              <ul class="team-social list-inline">
                <li><a href="about.html#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="about.html#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="about.html#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="about.html#"><i class="fa fa-envelope"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="team-member">
            <div class="member-image">
              <%= image_tag("team/3.jpg",  alt: "image", class: "img-responsive") %>
            </div>
            <div class="team-info">
              <div class="member-info">
                <h4>Abir Ahnan</h4>
                <p>Chief Engineer</p>
              </div>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod fore to tempor incididunt.</p>
              <ul class="team-social list-inline">
                <li><a href="about.html#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="about.html#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="about.html#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="about.html#"><i class="fa fa-envelope"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="team-member">
            <div class="member-image">
              <%= image_tag("team/1.jpg",  alt: "image", class: "img-responsive") %>
            </div>
            <div class="team-info">
              <div class="member-info">
                <h4>Mark Leon</h4>
                <p>Cheaf Colnsultant</p>
              </div>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod fore to tempor incididunt.</p>
              <ul class="team-social list-inline">
                <li><a href="about.html#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="about.html#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="about.html#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="about.html#"><i class="fa fa-envelope"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="team-member">
            <div class="member-image">
              <%= image_tag("team/2.jpg",  alt: "image", class: "img-responsive") %>
            </div>
            <div class="team-info">
              <div class="member-info">
                <h4>Steve Clark</h4>
                <p>Project Manager</p>
              </div>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod fore to tempor incididunt.</p>
              <ul class="team-social list-inline">
                <li><a href="about.html#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="about.html#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="about.html#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="about.html#"><i class="fa fa-envelope"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>&lt;!&ndash; container &ndash;&gt;
</div>&lt;!&ndash; team section &ndash;&gt;

<div class="testimonial-section image-bg section-padding">
  <div class="overlay"></div>
  <div class="container">
    <div class="testimonial-slider">

      <div class="row testimonial text-center">
        <div class="col-sm-8 col-sm-offset-2">
          <div class="testimonial-image">
            <%= image_tag("testimonial/1.jpg",  alt: "image", class: "img-responsive") %>
          </div>
          <div class="testimonial-info ">
            <p>Lorem Ipsum is simply dummy text of the printing and pesetting to industry. Lorem Ipsum has been the industry's standard dummy tet ever since they 1500s, </p>
            <h5>Jhon Doe | CEO, Eric Consultancy</h5>
          </div>
        </div>

      </div>
      <div class="row testimonial text-center">
        <div class="col-sm-8 col-sm-offset-2">
          <div class="testimonial-image">
            <%= image_tag("testimonial/2.jpg",  alt: "image", class: "img-responsive") %>
          </div>
          <div class="testimonial-info">
            <p>Lorem Ipsum is simply dummy text of the printing and pesetting to industry. Lorem Ipsum has been the industry's standard dummy tet ever since they 1500s, </p>
            <h5>Mark Semouel | Vice Pricedent, KRBP</h5>
          </div>
        </div>

      </div>

      <div class="row testimonial text-center">
        <div class="col-sm-8 col-sm-offset-2">
          <div class="testimonial-image">
            <%= image_tag("testimonial/3.jpg",  alt: "image", class: "img-responsive") %>
          </div>
          <div class="testimonial-info">
            <p>Lorem Ipsum is simply dummy text of the printing and pesetting to industry. Lorem Ipsum has been the industry's standard dummy tet ever since they 1500s, </p>
            <h5>Hall Melan | Developer, Artsell</h5>
          </div>
        </div>

      </div>

    </div>
  </div>&lt;!&ndash; container &ndash;&gt;
</div>&lt;!&ndash; testimonial section &ndash;&gt;-->

<%= render "layouts/shared/link-contact" %>
<%= render "layouts/shared/footer" %>

app/views/welcome/index.html.erb
<% title "Bienvenue" %>

<%= render "layouts/shared/header" %>

<div class="home-section image-bg">
  <div class="overlay"></div>
  <div class="home-content">
    <div class="container">
      <div id="home-slider" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <h2>Construisez vos rêves avec le <span>Groupe OBERLIN</span></h2>
            <a href="/contact" class="btn btn-primary">Contactez-Nous Maintenant</a>
          </div>
          <div class="item">
            <h2>Vous recherchez des batisseurs <span>competents</span> ?</h2>
            <a href="/contact" class="btn btn-primary">Contactez-Nous Maintenant</a>
          </div>
          <div class="item">
            <h2>Des projets avec un <br><span>avenir sûr</span></h2>
            <a href="/contact" class="btn btn-primary">Contactez-Nous Maintenant</a>
          </div>
        </div>
        <a class="carousel-left" href="#home-slider" data-slide="prev"><i class="fa fa-angle-left"></i></a>
        <a class="carousel-right" href="#home-slider" data-slide="next"><i class="fa fa-angle-right"></i></a>
      </div>
    </div><!-- container -->
  </div><!-- home content -->

</div><!-- home -->

<div class="service-section section-padding">
  <div class="container">
    <div class="service-content">
      <div class="services">
        <div class="row">
          <div class="col-sm-6 col-md-4">
            <div class="service crane-lifting image-bg image-service-1">
              <div class="overlay"></div>
              <a href="/oberlin-agro">
                <div class="image-box">
                  <%= image_tag("img-services-1.jpg",  alt: "Image", class: "img-responsive") %>
                </div>
                <div class="box-title">
                  <h3>Oberlin <br>Agro</h3>
                  <p>Votre partenaire en Agriculture, élevage, pisciculture, Apiculture.</p>
                </div>
              </a>
            </div>
          </div>
          <div class="col-sm-6 col-md-4">
            <div class="service home-plumbing image-bg">
              <div class="overlay"></div>
              <a href="/oberlin-arts">
                <div class="image-box">
                  <%= image_tag("img-services-2.jpg",  alt: "Image", class: "img-responsive") %>
                </div>
                <div class="box-title">
                  <h3>Oberlin <br>Arts</h3>
                  <p>Agence de production <br>et de promotion <br> artistique.</p>
                </div>
              </a>
            </div>
          </div>
          <div class="col-sm-6 col-md-4">
            <div class="service home-plumbing image-bg">
              <div class="overlay"></div>
              <a href="/oberlin-construction">
                <div class="image-box">
                  <%= image_tag("img-services-3.jpg",  alt: "Image", class: "img-responsive") %>
                </div>
                <div class="box-title">
                  <h3>Oberlin <br>Construction</h3>
                  <p>Partenaire <br>pour vos projets <br>de construction.</p>
                </div>
              </a>
            </div>
          </div>
          <div class="col-sm-6 col-md-4">
            <div class="service house-plans image-bg">
              <div class="overlay"></div>
              <a href="/oberlin-immo">
                <div class="image-box">
                  <%= image_tag("img-services-4.jpg",  alt: "Image", class: "img-responsive") %>
                </div>
                <div class="box-title">
                  <h3>Oberlin <br>Immo</h3>
                  <p>Location, <br>vente, achat et <br>gestion immobilière.</p>
                </div>
              </a>
            </div>
          </div>
          <div class="col-sm-6 col-md-4">
            <div class="service house-plans image-bg">
              <div class="overlay"></div>
              <a href="/oberlin-ingenierie" >
                <div class="image-box">
                  <%= image_tag("img-services-5.jpg",  alt: "Image", class: "img-responsive") %>
                </div>
                <div class="box-title">
                  <h3>Oberlin <br>Ingenierie</h3>
                  <p>Spécialisé dans le calcul, la conception, l’optimisation et les études d’exécution</p>
                </div>
              </a>
            </div>
          </div>
          <div class="col-sm-6 col-md-4">
            <div class="service home-plumbing image-bg">
              <div class="overlay"></div>
              <a href="/oberlin-it">
                <div class="image-box">
                  <%= image_tag("img-services-6.jpg",  alt: "Image", class: "img-responsive") %>
                </div>
                <div class="box-title">
                  <h3>Oberlin <br>IT</h3>
                  <p>Solutions <br> informatiques <br>et TIC.</p>
                </div>
              </a>
            </div>
          </div>
          <div class="col-sm-6 col-md-4">
            <div class="service house-plans image-bg">
              <div class="overlay"></div>
              <a href="/oberlin-services">
                <div class="image-box">
                  <%= image_tag("img-services-7.jpg",  alt: "Image", class: "img-responsive") %>
                </div>
                <div class="box-title">
                  <h3>Oberlin <br>Services</h3>
                  <p>Un prestataire de services devoué.</p>
                </div>
              </a>
            </div>
          </div>
          <div class="col-sm-6 col-md-4">
            <div class="service house-plans image-bg">
              <div class="overlay"></div>
              <a href="/oberlin-tourisme">
                <div class="image-box">
                  <%= image_tag("tourism/tourism.png",  alt: "Image", class: "img-responsive") %>
                </div>
                <div class="box-title">
                  <h3>Oberlin <br>Tourisme</h3>
                  <p>Votre promoteur touristique</p>
                </div>
              </a>
            </div>
          </div>
          <div class="col-sm-6 col-md-4">
            <div class="service home-plumbing image-bg">
              <div class="overlay"></div>
              <a href="/oberlin-transit">
                <div class="image-box">
                  <%= image_tag("img-services-9.jpg",  alt: "Image", class: "img-responsive") %>
                </div>
                <div class="box-title">
                  <h3>Oberlin <br>Transit</h3>
                  <p>Votre Assistant <br> import-export</p>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div><!-- services -->
    </div>
  </div><!-- container -->
</div><!-- service section -->

<div class="testimonial-section image-bg section-padding">
  <div class="overlay"></div>
  <div class="container">
    <div class="testimonial-slider">

      <div class="row testimonial text-center">
        <div class="col-sm-8 col-sm-offset-2">
          <div class="testimonial-image">
            <%= image_tag("testimonial/1.jpg",  alt: "image", class: "img-responsive") %>
          </div>
          <div class="testimonial-info ">
            <p>Lorem Ipsum is simply dummy text of the printing and pesetting to industry. Lorem Ipsum has been the industry's standard dummy tet ever since they 1500s, </p>
            <h5>Jhon Doe | CEO, Eric Consultancy</h5>
          </div>
        </div>

      </div>
      <div class="row testimonial text-center">
        <div class="col-sm-8 col-sm-offset-2">
          <div class="testimonial-image">
            <%= image_tag("testimonial/2.jpg",  alt: "image", class: "img-responsive") %>
          </div>
          <div class="testimonial-info">
            <p>Lorem Ipsum is simply dummy text of the printing and pesetting to industry. Lorem Ipsum has been the industry's standard dummy tet ever since they 1500s, </p>
            <h5>Mark Semouel | Vice Pricedent, KRBP</h5>
          </div>
        </div>

      </div>

      <div class="row testimonial text-center">
        <div class="col-sm-8 col-sm-offset-2">
          <div class="testimonial-image">
            <%= image_tag("testimonial/3.jpg",  alt: "image", class: "img-responsive") %>
          </div>
          <div class="testimonial-info">
            <p>Lorem Ipsum is simply dummy text of the printing and pesetting to industry. Lorem Ipsum has been the industry's standard dummy tet ever since they 1500s, </p>
            <h5>Hall Melan | Developer, Artsell</h5>
          </div>
        </div>

      </div>

    </div>
  </div><!-- container -->
</div><!-- testimonial section -->

<div class="blog-section section-padding">
  <div class="container">
    <div class="section-title text-center">
      <h1>News</h1>
      <h2>Restez Informé à Propos de Nous</h2>
    </div>
    <div class="blog-content">
      <div class="row">
      <% @articles.each do |article|%>
        <div class="col-md-4 col-sm-6">
          <div class="blog-post">
            <div class="entry-header">
              <div class="blog-image">
                <div class="entry-thumbnail">
                  <%= link_to "/news-details" do %>
                      <%= image_tag(('blog/1.jpg'), :class => "img-responsive", :alt => "Blog Image") %>
                  <% end %>
                </div>
                <div class="time">
                  <h2><%=article.created_at.strftime("%d")%> <span><%=article.created_at.strftime("%B")%></span></h2>
                </div>
              </div> <!-- blog-image -->
            </div>
            <div class="entry-post">
              <div class="entry-title">
                <h4><a href="blog-details.html"><%= article.article_title%></a></h4>
              </div>
              <div class="post-content">
                <div class="entry-summary">
                  <p>
                    <%=truncate(article.article_description, length: 150) %> <%= link_to "Read more", news_details_url(article.id)%>
                  </p>
                  <div class="entry-meta">
                    <ul class="list-inline">
                      <li><a><i class="fa fa-user"></i><%=article.post_by.capitalize %></a></li>
                      <li><a><i class="fa fa-folder-o"></i><%=article.category%></a></li>
                      <li>
                        <a href="/news-details/<%=article.id%>#comment"><i class="fa fa-comment-o"></i><%=pluralize(article.comments.count, "Comment")%></a>
                       </li>
                    </ul>
                  </div>

                </div>
              </div>
            </div><!-- entry-post -->
          </div>
        </div>
       <%end%>
        
      </div><!-- row -->
    </div><!-- blog content -->
  </div><!-- container -->
</div><!-- blog section -->

<%= render "layouts/shared/link-contact" %>
<%= render "layouts/shared/footer" %>