config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'Groupe-Oberlin/', to: 'users#show'
    get 'Groupe-Oberlin/new-article', to: 'users#new_article'
    post 'Groupe-Oberlin/new-article', to: 'users#create_article'
    get 'Groupe-Oberlin/article/:id', to: 'users#article', as: 'Groupe-Oberlin/article/'
    get 'Groupe-Oberlin/Messages', to: 'users#messages'
    get 'Groupe-Oberlin/Comments', to: 'users#comments'
  end

  get 'admin/login', to: 'sessions#new'
  post 'admin/login', to: 'sessions#create'
  delete 'admin/logout', to: 'sessions#destroy'

  get 'news-details/:id' => 'news#show', as: 'news-details'
  post 'news-details/:id' => 'news#comment'

  get 'emploi' => 'emploi#index'

  get 'faq' => 'contact#faq'

  get 'contact' => 'contact#index'
  post 'contact' => 'contact#send_message'

  get 'a-propos' => 'welcome#a-propos'

  get 'news' => 'news#index'

  get 'oberlin-transit' => 'filliales#transit'

  get 'oberlin-tourisme' => 'filliales#tourisme'

  get 'oberlin-services' => 'filliales#services'

  get 'oberlin-it' => 'filliales#it'

  get 'oberlin-ingenierie' => 'filliales#ingenierie'

  get 'oberlin-immo' => 'filliales#immo'

  get 'oberlin-construction' => 'filliales#construction'

  get 'oberlin-arts' => 'filliales#arts'

  get 'oberlin-agro' => 'filliales#agro'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authorized
  def show
  end
  def messages
  	@messages = Contact.all
  end
  def comments
  	
  end
  def new_article
  	@blog = Blog.new
  end
  def create_article
  	@article = Blog.new(article_params)
  	@article.post_by = current_admin.name
  	if @article.save
  		#do redirect to show
  		flash[:notice] = "Article posted!"
  		redirect_to admin_Groupe_Oberlin_article_url(@article)
  	else
  		#tell the users of what errors he/she has
  		render 'new_article'
  	end
  end
  def article
  	@article = Blog.find_by(id: params[:id])
  end


  private
  	def article_params
  		params.require(:blog).permit(:article_title, 
  									:article_description,
  									:post_by, :category,
  									:image)
  	end
  	def authorized
  		unless current_admin 
  			redirect_to root_path
  		end
  	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/shared/_admin_header_links.html.erb
<header id="header">
  <div class="top-bar">
    <div class="container">
      <div class="row">
        <div class="col-sm-8">
          <div class="info-box">
            <i class="fa fa-envelope"></i>
            <div class="info-text">
              <h5>E-mail :</h5>
              <a href="#">hello@groupeoberlin.com</a>
            </div>
          </div>
          <div class="info-box">
            <i class="fa fa-phone"></i>
            <div class="info-text">
              <h5>Contact :</h5>
              <span>+237 243-434-567</span>
            </div>
          </div>
          <div class="info-box">
            <i class="fa fa-clock-o"></i>
            <div class="info-text">
              <h5>Heures d'ouverture :</h5>
              <a href="#">Lundi - Samedi : 8h30 - 17h30</a>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
          <div class="top-social pull-right">
            <ul class="list-inline">
              <li><a href="#" target="_blank"><i class="fa fa-facebook-square"></i></a></li>
              <li><a href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#" target="_blank"><i class="fa fa-linkedin-square"></i></a></li>
            </ul>

          </div>
        </div>
      </div>
    </div><!-- container -->
  </div><!-- top-bar -->

  <div class="main-menu">
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/admin/Groupe-Oberlin"><%= image_tag("logo.png",  alt: "Logo", class: "img-responsive") %></a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to 'Post an article',admin_Groupe_Oberlin_new_article_path%>
          </li>
            <li class="dropdown">
              <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                See more
                <i class="fa fa-caret-down" aria-hidden="true"></i>
              </a>
              <ul class="dropdown-menu">
                <li>
                <%=link_to 'Messages', admin_Groupe_Oberlin_Messages_path %></li>
                <li>
                <%= link_to 'Comments', admin_Groupe_Oberlin_Comments_path%>
                </li>
                <li>
                  <%= link_to 'Post article',admin_Groupe_Oberlin_new_article_path%> 
                </li>
                
              </ul>
            </li>
            
            <li class="">
               <%=link_to 'logout', admin_logout_url, method: :delete %>
            </li>
            
          </ul>
        </div>
      </div><!-- container -->
    </nav><!-- navbar -->
  </div><!-- main menu -->
</header><!-- Header -->

app/views/admin/users/shared/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <!-- <div>
        The form has <%= pluralize(object.errors.count, "error") %>.
      </div> -->
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>