config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'Groupe-Oberlin/', to: 'users#show'
    get 'Groupe-Oberlin/new-article', to: 'users#new_article'
    post 'Groupe-Oberlin/new-article', to: 'users#create_article'
    get 'Groupe-Oberlin/article/:id', to: 'users#article', as: 'Groupe-Oberlin/article/'
    get 'Groupe-Oberlin/Messages', to: 'users#messages'
    get 'Groupe-Oberlin/Comments', to: 'users#comments'
  end

  get 'admin/login', to: 'sessions#new'
  post 'admin/login', to: 'sessions#create'
  delete 'admin/logout', to: 'sessions#destroy'

  get 'news-details/:id' => 'news#show', as: 'news-details'
  post 'news-details/:id' => 'news#comment'

  get 'emploi' => 'emploi#index'

  get 'faq' => 'contact#faq'

  get 'contact' => 'contact#index'
  post 'contact' => 'contact#send_message'

  get 'a-propos' => 'welcome#a-propos'

  get 'news' => 'news#index'

  get 'oberlin-transit' => 'filliales#transit'

  get 'oberlin-tourisme' => 'filliales#tourisme'

  get 'oberlin-services' => 'filliales#services'

  get 'oberlin-it' => 'filliales#it'

  get 'oberlin-ingenierie' => 'filliales#ingenierie'

  get 'oberlin-immo' => 'filliales#immo'

  get 'oberlin-construction' => 'filliales#construction'

  get 'oberlin-arts' => 'filliales#arts'

  get 'oberlin-agro' => 'filliales#agro'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :name, presence: true
	validates :subject, presence: true
	validates :email, presence: true
	validates :message, presence: true

	before_save { self.message = message.rstrip }
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  	@contact = Contact.new
  end
  def send_message
  	@contact = Contact.new(contact_params)
  	 if @contact.save
  	 	flash[:notice] = "Message sent!"
  	 	redirect_to :back
  	 else
  	 	render 'index'
  	 end
  end


  private
  def contact_params
  	params.require(:contact).permit(:name, :subject, :email, :message)
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/faq.html.erb
<h1>Contact#faq</h1>
<p>Find me in app/views/contact/faq.html.erb</p>

app/views/contact/index.html.erb
<% title "Contact" %>

<%= render "layouts/shared/header" %>

<div class="breadcrumb-section image-bg ">
  <div class="overlay"></div>
  <div class="breadcrumb-content container">
    <h1>Contactez-Nous</h1>
    <ol class="breadcrumb">
      <li><a href="/">Accueil</a></li>
      <li class="active">Contact</li>
    </ol>
  </div>
</div><!-- breadcrumb-section -->

<div class="contact-form-section section-padding">
  <div class="container">
    <div class="section-title text-center">
      <div class="container">
        <h2>Remplissez le formulaire</h2>
        <%if flash[:notice].present? %>
          <p><%=flash[:notice]%></p>
        <%end%>
        
      </div>
    </div>
    <div class="contact-info">
     <!--  <form id="contact-form" class="contact-form" name="contact-form"> -->
       
        <%= form_for(@contact, url: contact_url, :html => {class: 'contact-form', id: 'contact-form', method: :post}) do |f|%>
           <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <i class="fa fa-user" aria-hidden="true"></i>
              
              <%=f.text_field :name, class: 'form-control control-1', required: 'required', placeholder: 'Nom & Prénom' %>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="form-group">
              <i class="fa fa-th-list" aria-hidden="true"></i>
            
              <%=f.text_field :subject, class: 'form-control', required: 'required', placeholder: 'Objet' %>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="form-group">
              <i class="fa fa-envelope-o" aria-hidden="true"></i>
              <%=f.email_field :email, class: 'form-control', required: 'required', placeholder: 'E-mail' %>
            </div>
          </div>

          <div class="col-sm-12">
            <div class="form-group">
              <i class="fa fa-comments" aria-hidden="true"></i>
              
              <%=f.text_area :message, id: 'message', class: 'form-control', rows: 7, placeholder: 'Message' %>
            </div>
          </div>
        </div>
        <div class="submit-button">
          <%= f.submit "Envoyer", class: 'btn btn-primary'%>
        </div>
        <%end%>
      <!-- </form> --><!-- contact form -->
    </div>
  </div><!-- container -->
</div><!-- contact form section -->

<%= render "layouts/shared/footer" %>